CREATE STATISTICS [MANUAL_C_ACCTBAL] ON [customer](c_acctbal) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_C_ADDRESS] ON [customer](c_address) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_C_COMMENT] ON [customer](c_comment) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_C_CUSTKEY] ON [customer](c_custkey) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_C_MKTSEGMENT] ON [customer](c_mktsegment) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_C_NAME] ON [customer](c_name) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_C_NATIONKEY] ON [customer](c_nationkey) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_C_PHONE] ON [customer](c_phone) WITH SAMPLE 100 PERCENT
 
GO
CREATE STATISTICS [MANUAL_L_COMMENT] ON [lineitem](l_comment) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_L_COMMITDATE] ON [lineitem](l_commitdate) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_L_DISCOUNT] ON [lineitem](l_discount) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_L_EXTENDEDPRICE] ON [lineitem](l_extendedprice) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_L_LINENUMBER] ON [lineitem](l_linenumber) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_L_LINESTATUS] ON [lineitem](l_linestatus) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_L_ORDERKEY] ON [lineitem](l_orderkey) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_L_PARTKEY] ON [lineitem](l_partkey) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_L_QUANTITY] ON [lineitem](l_quantity) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_L_RECEIPTDATE] ON [lineitem](l_receiptdate) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_L_RETURNFLAG] ON [lineitem](l_returnflag) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_L_SHIPDATE] ON [lineitem](l_shipdate) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_L_SHIPINSTRUCT] ON [lineitem](l_shipinstruct) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_L_SHIPMODE] ON [lineitem](l_shipmode) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_L_SUPPKEY] ON [lineitem](l_suppkey) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_L_TAX] ON [lineitem](l_tax) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_N_COMMENT] ON [nation](n_comment) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_N_NAME] ON [nation](n_name) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_N_NATIONKEY] ON [nation](n_nationkey) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_N_REGIONKEY] ON [nation](n_regionkey) WITH SAMPLE 100 PERCENT
GO
 
CREATE STATISTICS [MANUAL_O_CLERK] ON [orders](o_clerk) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_O_COMMENT] ON [orders](o_comment) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_O_CUSTKEY] ON [orders](o_custkey) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_O_ORDERDATE] ON [orders](o_orderdate) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_O_ORDERKEY] ON [orders](o_orderkey) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_O_ORDERPRIORITY] ON [orders](o_orderpriority) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_O_ORDERSTATUS] ON [orders](o_orderstatus) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_O_SHIPPRIORITY] ON [orders](o_shippriority) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_O_TOTALPRICE] ON [orders](o_totalprice) WITH SAMPLE 100 PERCENT
GO
 
CREATE STATISTICS [MANUAL_P_BRAND] ON [part](p_brand) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_P_COMMENT] ON [part](p_comment) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_P_CONTAINER] ON [part](p_container) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_P_MFGR] ON [part](p_mfgr) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_P_NAME] ON [part](p_name) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_P_PARTKEY] ON [part](p_partkey) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_P_RETAILPRICE] ON [part](p_retailprice) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_P_SIZE] ON [part](p_size) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_P_TYPE] ON [part](p_type) WITH SAMPLE 100 PERCENT
GO
 
CREATE STATISTICS [MANUAL_PS_AVAILQTY] ON [partsupp](ps_availqty) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_PS_COMMENT] ON [partsupp](ps_comment) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_PS_PARTKEY] ON [partsupp](ps_partkey) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_PS_SUPPKEY] ON [partsupp](ps_suppkey) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_PS_SUPPLYCOST] ON [partsupp](ps_supplycost) WITH SAMPLE 100 PERCENT
GO
 
CREATE STATISTICS [MANUAL_R_COMMENT] ON [region](r_comment) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_R_NAME] ON [region](r_name) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_R_REGIONKEY] ON [region](r_regionkey) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_S_ACCTBAL] ON [supplier](s_acctbal) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_S_ADDRESS] ON [supplier](s_address) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_S_COMMENT] ON [supplier](s_comment) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_S_NAME] ON [supplier](s_name) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_S_NATIONKEY] ON [supplier](s_nationkey) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_S_PHONE] ON [supplier](s_phone) WITH SAMPLE 100 PERCENT
GO
CREATE STATISTICS [MANUAL_S_SUPPKEY] ON [supplier](s_suppkey) WITH SAMPLE 100 PERCENT
GO